version: '3.1'
services:

  manpower-inc:
    image: manpower.inc/manpower-inc
    restart: always
    ports:
    - 8082:8082
    environment:
      DB_SERVER: manpower-inc-db
      DB_PORT: 3306
      DB_NAME: manpower-inc-db
      DB_USER: testUser
      DB_PASSWORD: 1234
      APPLICATION_PORT: 8082
      USER_NAME: user
      USER_PASSWORD: user
      ADMIN_NAME: admin
      ADMIN_PASSWORD: admin
    depends_on:
        - manpower-inc-db
    networks:
    - manpower-nt

networks:
  manpower-nt: