spring:
  datasource:
    url: jdbc:mysql://${DB_SERVER:localhost}:${DB_PORT:3306}/${DB_NAME:manpower-inc-db}?useSSL=false
    username: ${DB_USER:testUser}
    password: ${DB_PASSWORD:1234}
server:
  port: ${APPLICATION_PORT:8082}
logging:
  level:
    se.cambio.cm.keyword: DEBUG
users:
  user:
    name: ${USER_NAME:user}
    password: ${USER_PASSWORD:user}
  admin:
    name: ${ADMIN_NAME:admin}
    password: ${ADMIN_PASSWORD:admin}