---
apiVersion: v1
kind: Service
metadata:
  name: manpower-app-data
spec:
  ports:
  - port: 3306
  selector:
    app: manpower-db
  clusterIP: None

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manpower-db
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: manpower-db
        - name: MYSQL_USER
          value: testUser
        - name: MYSQL_PASSWORD
          value: '1234'
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: manpower-db-data

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: manpower-db-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast
  resources:
    requests:
      storage: 1Gi
